CREATE TABLE Businesses (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  Phone_number VARCHAR(255) NOT NULL,
  Website VARCHAR(255) NOT NULL,
  Category VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE categories (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
